"""add_input_file_pipeline_run_id

Revision ID: 0fdcb8c02dd0
Revises: bbfac1d325be
Create Date: 2020-11-11 19:12:42.398375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '0fdcb8c02dd0'
down_revision = 'bbfac1d325be'
branch_labels = None
depends_on = None

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
tables = inspector.get_table_names()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_name not in tables:
        op.add_column('organization_pipeline_input_file', sa.Column('organization_pipeline_run_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'organization_pipeline_input_file', 'organization_pipeline_run', ['organization_pipeline_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_pipeline_input_file', type_='foreignkey')
    op.drop_column('organization_pipeline_input_file', 'organization_pipeline_run_id')
    # ### end Alembic commands ###
