"""input file to pipeline run

Revision ID: 34c2fcfd8aed
Revises: c0de2a9adaca
Create Date: 2020-11-12 14:37:15.869805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '34c2fcfd8aed'
down_revision = 'c0de2a9adaca'
branch_labels = None
depends_on = None

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
tables = inspector.get_table_names()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if "artifact_chart" not in tables:
        op.alter_column('artifact_chart', 'chart_config',
                existing_type=postgresql.JSON(astext_type=sa.Text()),
                nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifact_chart', 'chart_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
