"""add_org_workflow_models

Revision ID: a0e54652a189
Revises: 0fdcb8c02dd0
Create Date: 2020-11-10 16:15:02.067607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e54652a189'
down_revision = '0fdcb8c02dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_workflow_pipeline_run')
    op.drop_table('organization_workflow_pipeline')
    op.drop_table('organization_workflow')
    # ### end Alembic commands ###
