"""add_is_deleted_flag_to_charts

Revision ID: bbaf6bedc4c6
Revises: 34c2fcfd8aed
Create Date: 2020-12-08 14:30:02.579461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbaf6bedc4c6'
down_revision = '34c2fcfd8aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_workflow_pipeline_run', type_='foreignkey')
    op.drop_column('organization_workflow_pipeline_run', 'organization_workflow_run_id')
    op.drop_column('artifact_chart', 'is_deleted')
    op.drop_table('organization_workflow_run')
    # ### end Alembic commands ###
