"""create organization_pipeline and application permissions

Revision ID: eadaab8c0d84
Revises: 
Create Date: 2020-10-08 14:10:47.595101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eadaab8c0d84"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("applicationsystempermission")
    op.drop_table("systempermission")
    op.drop_table("organization_pipeline")
    op.drop_table("application")
    # ### end Alembic commands ###
