"""make_share_password_nullable

Revision ID: f9899ada778b
Revises: 8c08da3b521c
Create Date: 2020-10-29 18:08:28.476155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'f9899ada778b'
down_revision = '8c08da3b521c'
branch_labels = None
depends_on = None

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
tables = inspector.get_table_names()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if "organization_pipeline_run" not in tables:
        op.alter_column('organization_pipeline_run', 'share_password_hash',
                existing_type=sa.VARCHAR(length=127),
                nullable=True)
        op.alter_column('organization_pipeline_run', 'share_password_salt',
                existing_type=sa.VARCHAR(length=127),
                nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_pipeline_run', 'share_password_salt',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)
    op.alter_column('organization_pipeline_run', 'share_password_hash',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)
    # ### end Alembic commands ###
